/* 
 * Accounts Api
 *
 * API for accessing the Accounts subsystem. Currently, only invitation procedures are implemented.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Iatec.Apis.Accounts.v1.Client.Api;
using Iatec.Apis.Accounts.v1.Client.Model;
using Iatec.Apis.Accounts.v1.Client.Client;
using System.Reflection;

namespace Iatec.Apis.Accounts.v1.Client.Test
{
    /// <summary>
    ///  Class for testing ErrorModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class ErrorModelTests
    {
        // TODO uncomment below to declare an instance variable for ErrorModel
        //private ErrorModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorModel
            //instance = new ErrorModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorModel
        /// </summary>
        [TestMethod]
        public void ErrorModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorModel
            //Assert.IsInstanceOfType<ErrorModel> (instance, "variable 'instance' is a ErrorModel");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [TestMethod]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [TestMethod]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
