/* 
 * Accounts Api
 *
 * API for accessing the Accounts subsystem. Currently, only invitation procedures are implemented.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Iatec.Apis.Accounts.v1.Client.Api;
using Iatec.Apis.Accounts.v1.Client.Model;
using Iatec.Apis.Accounts.v1.Client.Client;
using System.Reflection;

namespace Iatec.Apis.Accounts.v1.Client.Test
{
    /// <summary>
    ///  Class for testing LinkedUserModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class LinkedUserModelTests
    {
        // TODO uncomment below to declare an instance variable for LinkedUserModel
        //private LinkedUserModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of LinkedUserModel
            //instance = new LinkedUserModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LinkedUserModel
        /// </summary>
        [TestMethod]
        public void LinkedUserModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LinkedUserModel
            //Assert.IsInstanceOfType<LinkedUserModel> (instance, "variable 'instance' is a LinkedUserModel");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [TestMethod]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [TestMethod]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [TestMethod]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
