/* 
 * Accounts Api
 *
 * API for accessing the Accounts subsystem. Currently, only invitation procedures are implemented.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Iatec.Apis.Accounts.v1.Client.Api;
using Iatec.Apis.Accounts.v1.Client.Model;
using Iatec.Apis.Accounts.v1.Client.Client;
using System.Reflection;

namespace Iatec.Apis.Accounts.v1.Client.Test
{
    /// <summary>
    ///  Class for testing PagedUserModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class PagedUserModelTests
    {
        // TODO uncomment below to declare an instance variable for PagedUserModel
        //private PagedUserModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of PagedUserModel
            //instance = new PagedUserModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PagedUserModel
        /// </summary>
        [TestMethod]
        public void PagedUserModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PagedUserModel
            //Assert.IsInstanceOfType<PagedUserModel> (instance, "variable 'instance' is a PagedUserModel");
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [TestMethod]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [TestMethod]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [TestMethod]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [TestMethod]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
