/* 
 * Accounts Api
 *
 * API for accessing the Accounts subsystem. Currently, only invitation procedures are implemented.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Iatec.Apis.Accounts.v1.Client.Api;
using Iatec.Apis.Accounts.v1.Client.Model;
using Iatec.Apis.Accounts.v1.Client.Client;
using System.Reflection;

namespace Iatec.Apis.Accounts.v1.Client.Test
{
    /// <summary>
    ///  Class for testing PagedLinkedUserModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PagedLinkedUserModelTests
    {
        // TODO uncomment below to declare an instance variable for PagedLinkedUserModel
        //private PagedLinkedUserModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PagedLinkedUserModel
            //instance = new PagedLinkedUserModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PagedLinkedUserModel
        /// </summary>
        [Test]
        public void PagedLinkedUserModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PagedLinkedUserModel
            //Assert.IsInstanceOfType<PagedLinkedUserModel> (instance, "variable 'instance' is a PagedLinkedUserModel");
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
