/* 
 * Accounts Api
 *
 * API for accessing the Accounts subsystem. Currently, only invitation procedures are implemented.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Iatec.Apis.Accounts.v1.Client.Api;
using Iatec.Apis.Accounts.v1.Client.Model;
using Iatec.Apis.Accounts.v1.Client.Client;
using System.Reflection;

namespace Iatec.Apis.Accounts.v1.Client.Test
{
    /// <summary>
    ///  Class for testing UserModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserModelTests
    {
        // TODO uncomment below to declare an instance variable for UserModel
        //private UserModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserModel
            //instance = new UserModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserModel
        /// </summary>
        [Test]
        public void UserModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserModel
            //Assert.IsInstanceOfType<UserModel> (instance, "variable 'instance' is a UserModel");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Test]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }
        /// <summary>
        /// Test the property 'RegistrationComplete'
        /// </summary>
        [Test]
        public void RegistrationCompleteTest()
        {
            // TODO unit test for the property 'RegistrationComplete'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
